在……之上

操作/上载工件@v4:
推:
分支机构: [掌握]
workflow_dispatch:

工作:
建立:
连续的: Ubuntu-最新
步骤:
      - uses: 操作/结帐@v4

      - 姓名: 设置JDK17
uses: 操作/设置-Java@v4
和……一起:
分布: temurin
java版: 17

-姓名：设置Node.js
uses：操作/设置-节点@v4
和……一起:
节点版本: 20

-姓名: 安装pnpm
跑: npm安装-g pnpm

-姓名: 安装web-ui依赖项
跑: CD web-ui&&pnpm安装

-姓名: 构建调试安装包
跑: chmod+x gradlew&&./gradlew装配调试

-姓名: 上传安装包
uses: 操作/上载工件@v4
和……一起:
姓名: orangechat-debug
路径: app/build/outputs/apk/debug/*.apk
